---
text:
childText:
  - text:
      en: "I have a question about GenLauncher"
      ru: "У меня вопрос по ГенЛаунчеру"
    childText:
      - text:
          en: "How to download GenLauncher"
          ru: "Где скачать Генлаунчер"
        childText:
          - text:
              en: "Check download channel"
              ru: "Посмотри канал download"
            func: return_text
      - text:
          en: "When mod will be added in GenLauncher?"
          ru: "Когда добавят мод в ГенЛаунчер?"
        childText:
          - text:
              en: "Mods are added to the launcher only with the initiative - or consent - of the mod creator and only if the mod has a valid ModDB page. You may get in touch with the mod creator and give him DeL's discord profile ID in order to arrange the process."
              ru: "Моды в лаунчер добавляются по инициативе автора мода и только при наличии страницы на moddb. Ты можешь связаться с автором мода и попросить его добавить мод в генлаунчер, дав контакты разработчика DeL"
            func: return_text
      - text:
          en: "How to install addon or patch via GenLauncher?"
          ru: "Как установить аддон или патч через ГенЛаунчер?"
        childText:
          - text:
              en: "Select mod on main tab and after that click on button addons or patches, there you will be able to add or install addons for selected mod"
              ru: "Выбери мод на главной вкладке и после этого кликни на кнопку addons или patches, здесь будет можно установить или скачать аддоны и патчи к выбранному моду"
            func: return_text
      - text:
          en: "I have an idea for GenLauncher"
          ru: "У меня есть идея/пожелание для ГенЛаунчера"
        childText:
          - text:
              en: "You can write your idea in the feedback channel, GenLauncher developer will definitely read it)"
              ru: "Ты можешь написать свою идею в канале отзывы, разработчик Генлаунчера обязательно ознакомится с ней)"
            func: return_text
      - text:
          en: "How i can support development of GenLauncher?"
          ru: "Как я могу поддержать разработку ГенЛаунчера?"
        childText:
          - text:
              en: "You can donate $ to author of GenLauncher (support channel) and/or express your wish in feedback channel"
              ru: "Ты можешь поддержать автора денежно (канал support) и/или высказав свою идею/пожелание в канале отзывы"
            func: return_text
      - text:
          en: "I have an error while using GenLauncher"
          ru: "У меня возникает ошибка при использовании ГенЛаунчера"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots, including the following information: When the problem happened; How the problem manifests itself (error message or unintended behavior); How to reproduce the problem step by step."
              ru: "Пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть проблемы, указав следующую информацию: в какой момент возникает ошибка; как проявляется ошибка (текст ошибки или какое-то некорректное поведение); что нужно сделать шаг за шагом, чтобы ошибка повторилась."
            func: ask_input
            targetId: 220196571868823562
  - text:
      en: "I have a question about one of the mods"
      ru: "У меня вопрос по одному из модов"
    childText:
      - text:
          en: "Rise of The Reds"
          ru: "Rise of The Reds"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "Пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 168777263242936321
      - text:
          en: "The End of Days (TEOD)"
          ru: "The End of Days (TEOD)"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "Пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 262545744890691584
      - text:
          en: "Contra"
          ru: "Contra"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 196736340224638976
      - text:
          en: "Operation Firestorm"
          ru: "Operation Firestorm"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 222240457717973004
      - text:
          en: "Shockwave"
          ru: "Shockwave"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "Пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 168777263242936321
      - text:
          en: "World War 2"
          ru: "World War 2"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "Пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 248807823184625665
      - text:
          en: "Zero Hour Reborn"
          ru: "Zero Hour Reborn"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 221480812489474048
      - text:
          en: "NProject"
          ru: "NProject"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 221584201697329152
      - text:
          en: "CnC Untitled"
          ru: "CnC Untitled"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 221480812489474048
      - text:
          en: "Shockwave Chaos"
          ru: "Shockwave Chaos"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 269889853347463179
      - text:
          en: "The power of the West"
          ru: "The power of the West"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 492610159835873280
      - text:
          en: "Zero Hour Continue"
          ru: "Zero Hour Continue"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 709790636181815396
      - text:
          en: "C&C Tiberian Dawn Redux"
          ru: "C&C Tiberian Dawn Redux"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 879234202976002058
      - text:
          en: "Condition Zero"
          ru: "Condition Zero"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 221480812489474048
      - text:
          en: "Project Raptor"
          ru: "Project Raptor"
        childText:
          - text:
              en: "Please describe the issue in as much detail as possible, preferably with screenshots"
              ru: "На английском языке, пожалуйста, как можно подробнее, по возможностью со скриншотами опиши суть вопроса"
            func: ask_input
            targetId: 221480812489474048
  - text:
      en: "I have a question about Generals game"
      ru: "У меня вопрос по игре генералы"
    childText:
      - text:
          en: "Where can I download С&C Generals?"
          ru: "Где можно скачать С&C Generals?"
        childText:
          - text:
              en: "You can get licensed copy of Generals Zero Hour by purchasing C&C Ultimate Collection in Origin: https://www.origin.com/rus/en-us/store/command-and-conquer/command-and-conquer-the-ultimate-collection"
              ru: "Ты можешь получить лицензированную копию Generals Zero Hour, приобретя C&C Ultimate Collection в Origin: https://www.origin.com/rus/en-us/store/command-and-conquer/command-and-conquer-the-ultimate-collection"
            func: return_text
      - text:
          en: "My generals doesnt work"
          ru: "У меня не работают генералы"
        childText:
          - text:
              en: "This is GenLauncher Discord server, one of the requirements for the GenLauncher work is the presence of an Generals, it is assumed that you have them and work. Technical support for generals is not provided on this server"
              ru: "Это дискорд сервер по GenLauncherу, одним из требований для работы GenLauncher является наличие чистых и рабочих генералов, подразумевается что они у вас уже есть. Техническая поддержка по генералам на этом сервере не оказывается."
            func: return_text
            test
